# This workflow runs after a pull-request has been approved by a reviewer

name: CI Tests

on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review]


jobs:
  change-id-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check for Change-Id
        run: |
          for commit in $(git rev-list ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}); do
              git checkout $commit
              if (git log -1 --pretty=format:"%s" | grep -q "Change-Id: ")
              then
                exit 0
              fi
          done
          echo "One or more of the commits in this pull request is missing a Change-ID, which we require for any changes made to gem5. "\
            "To automatically insert one, run the following:\n f=`git rev-parse --git-dir`/hooks/commit-msg ; mkdir -p $(dirname $f) ; "\
            "curl -Lo $f https://gerrit-review.googlesource.com/tools/hooks/commit-msg ; chmod +x $f\n Then amend the commit with git commit --amend --no-edit, and update your pull request."
          exit 1
