# This workflow runs after a pull-request has been approved by a reviewer

name: CI Tests

on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          for commit in $(git rev-list ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}); do
              git checkout $commit
              if git log -1 --pretty=format:"%s" | grep -q "Change-Id: "
              then
                echo "Substring is found."
              else
                echo "Substring not found."
              fi
          done
