# This workflow runs after a pull-request has been approved by a reviewer

name: CI Tests

on:
  pull_request:
    types: [opened, edited, synchronize, ready_for_review]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          for commit in $(git rev-list ${{ github.event.before}}..${{ github.sha}}); do
              git checkout $commit
              git log -1 --pretty=format:"%s" >> test.txt
              string="This is a test string."
              substring="Change-Id: "
              if git log -1 --pretty=format:"%s" | grep -q "$substring"
              then
                echo "Substring found."
              else
                echo "Substring not found."
              fi
              echo "outside test"
          done
